blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>', cache_page(60)(BlogDetailView.as_view()), name='detail'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mydjangoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogapp.urls'))
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    content = models.TextField(verbose_name='Описание')
    slug = models.CharField(max_length=150, verbose_name='Slug', null=True, blank=True)
    preview = models.ImageField(upload_to='blog', verbose_name='Изображение', null=True, blank=True)
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    sign_publication = models.IntegerField(default=0, verbose_name='Просмотры')
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.title} {self.created_at} {self.sign_publication}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.core.mail import send_mail

from blog.models import Blog

from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from pytils.translit import slugify


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    @staticmethod
    def send_notification():
        send_mail(
            subject='Уведомление',
            message='Ваша блог достигл 100 просмотров!',
            from_email="@yandex.ru",
            recipient_list=[],
        )

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.sign_publication += 1
        self.object.save()

        if self.object.sign_publication >= 100:
            self.send_notification()

        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview', )
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview',)

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:list', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
<div class="album py-3 bg-body-tertiary">
    <div class="container text-center">
        <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p>Хотите удалить материал "{{ object.title }}"?</p>
                            <button type="submit" class="p-2 btn btn-danger">Да</button>
                            <a class="p-2 btn btn-warning" href="{% url 'blog:list' %}">Нет</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4 pb-md-2">{{ object.title }}</h1>
    {% if object.preview%}
        <img src="{{ object.preview|media_filter }}" style="max-height: 300px; max-width: 300px;" class="card-img-top"
                                 alt="Продукт">
    {% endif %}
    <p class="lead pt-md-3">{{ object.content }}</p>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
<div class="album py-3 bg-body-tertiary">
    <div class="container text-center">
        <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="post-form">
                                {{ form.as_p }}
                            </fieldset>
                            {% if object %}
                            <button type="submit" class="btn btn-primary">Изменить</button>
                            {% else %}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
{% load my_tags %}
<div class="container">
    <div class="row text-center">
        {% if object_list %}
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        {% if object.preview %}
                        <img src="{{ object.preview|media_filter }}" style="" class="card-img-top"
                             alt="Изображение">
                        <div class="text pt-md-3">{{ object.content|truncatechars:50 }}</div>
                        {% else %}
                        <div class="text pt-md-3">{{ object.content|truncatechars:50 }}</div>
                        <div class="text pt-md-3">Просмотры: {{ object.sign_publication }}</div>
                        {% endif %}
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'blog:detail' object.pk %}">Подробнее</a>
                    <span class="my-1"></span>

                    {% if user.is_authenticate %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'blog:update' object.pk %}">Изменить</a>
                    <span class="my-1"></span>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'blog:delete' object.pk %}">Удалить</a>
                    <span class="my-1"></span>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'blog:create' %}">Новая запись</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}

        {% else %}
            {% if user.is_active %}
                <div class="text-center">
                    <a class="btn btn-primary" href="{% url 'blog:create' %}">Создать новую запись</a>
                </div>
            {% else %}
                <h3 class="text pt-md-3">Для создания записи авторизуйтесь</h3>
            {% endif %}
        {% endif %}


    </div>
</div>
{% endblock %}