blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>', cache_page(60)(BlogDetailView.as_view()), name='detail'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (HomeTemplateView, ContactsTemplateView, ProductListView, ProductDetailView,
                           ProductDeleteView, ProductCreateView, ProductUpdateView, CategoryListView)

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('list/', ProductListView.as_view(), name='list'),
    path('detail/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='detail'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='update'),
    path('category/', CategoryListView.as_view(), name='list_category')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mydjangoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogapp.urls'))
]

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название категории", )
    description = models.TextField(verbose_name="Описание категории", **NULLABLE)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название продукта")
    description = models.TextField(verbose_name="Описание продукта", **NULLABLE)
    preview = models.ImageField(upload_to="products/", verbose_name="Фото продукта", **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name="Категория", related_name="Products",
                                 **NULLABLE)
    price = models.IntegerField(verbose_name="Цена продукта", **NULLABLE)
    created_at = models.DateField(verbose_name="Дата создания", **NULLABLE)
    updated_at = models.DateField(verbose_name="Дата изменения", **NULLABLE)

    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)
    is_published = models.BooleanField(verbose_name="Публикация", default=False, **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.description} {self.preview} {self.category} {self.price}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        permissions = [
            ('cancellation_of_publication', 'Canceling the publication of the product'),
            ('changes_the_description', 'Changes the description of any product'),
            ('changes_the_category', 'Changes the category of any product'),
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, verbose_name="Продукт", **NULLABLE)
    number = models.PositiveIntegerField(verbose_name="Номер версии продукта")
    name = models.CharField(max_length=150, verbose_name="Название версии")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.product}"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django.forms import ModelForm, forms

from catalog.models import Product, Version

forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа',
                   'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormsMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', 'is_published', 'owner')

    def clean_name(self):
        name = self.cleaned_data['name']
        if any(word in name for word in forbidden_words):
            raise forms.ValidationError(f'Cлова {", ".join(forbidden_words)} запрещены')
        return name

    def clean_description(self):
        description = self.cleaned_data['description']
        for word in forbidden_words:
            if word in description.lower():
                raise forms.ValidationError(f'Cлова {", ".join(forbidden_words)} запрещены')
            else:
                return description


class VersionForm(ModelForm):
    model = Version
    fields = '__all__'

catalog/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory, ModelForm
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, DeleteView, UpdateView

from catalog.forms import ProductForm, VersionForm, StyleFormsMixin
from catalog.models import Product, Version, Category
from config.services import get_cached_data


class HomeTemplateView(TemplateView):
    template_name = "catalog/home.html"


class ContactsTemplateView(TemplateView):
    template_name = 'catalog/contacts.html'

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        timestamp = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        with open('feedback.txt', 'a') as file:
            file.write(f'{timestamp}, {phone}, {name}: {message}\n')
        return super().get(request, *args, **kwargs)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')
    login_url = "users:login"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавить продукт'
        return context

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductModeratorForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Product
        fields = ['description', 'category', 'is_published']


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'

    def get_queryset(self):
        return get_cached_data(self.model)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, VersionForm, fields='__all__', extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (user.has_perm('catalog.cancellation_of_publication') and user.has_perm('catalog.changes_the_description')
                and user.has_perm('catalog.changes_the_category')):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (user.has_perm('cancellation_of_publication') and user.has_perm('changes_the_description')
                and user.has_perm('changes_the_category')):
            return ProductModeratorForm
        raise PermissionDenied


class CategoryListView(ListView):
    model = Category
    template_name = 'catalog/category_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории продуктов'
        return context

    def get_queryset(self):
        return get_cached_data(self.model)

catalog/templates/catalog/basic_template.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>
<div class="container">
    {% include 'catalog/includes/inc_menu.html' %}
    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts'%}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<!-- Bootstrap core JavaScript -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/catalog_product.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Продукты</h1>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <img src="{{ object.preview|media_filter }}" style="...    " class="card-img-top"
                             alt="Продукт">
                        <p class="text pt-md-3">{{ object.description|truncatechars:50 }}</p>
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:info_product' object.pk %}">О
                        продукте</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in category_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{object.description|slice:100}}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/basic_template.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Russia</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Мой адрес не дом и не улица</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message"
                                      placeholder="Введите ваше сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">Привет, друг</h2>
    <p class="lead">Я - главная страница сайта о товарах. Мой создатель только начал свой путь в веб разработке,
        многое у него не получается, но он очень пытается. Вот тебе картинка котиков, для отвлечения внимания.
        Для просмотра товаров жмякни на каталог </p>
    <img src="/media/cats/img.png"
         style="max-height: 393px; max-width: 273px;" class="card-img-top" alt="Кот">
    <img src="/media/cats/cute-kitten-clouds_23-2150752838.jpg"
         style="max-height: 600px; max-width: 650px;" class="card-img-top" alt="Кот">
    <img src="/media/cats/img_1.png"
         style="max-height: 393px; max-width: 276px;" class="card-img-top" alt="Кот">
</div>
{% endblock %}

catalog/templates/catalog/info_product.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4 pb-md-2">{{ object.name }}</h1>
    <img src="{{ object.preview|media_filter }}" style="max-height: 300px; max-width: 300px;" class="card-img-top"
                             alt="Продукт">
    <p class="lead pt-md-3">{{ object.description }}</p>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                <div class="col-12">
                    <div class="row">
                        <div class="col-8">
                            <div class="card">
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <p> Хотите удалить "{{ object.name }}"? </p>
                                        <button type="submit" class="btn btn-lg btn-block btn-danger">
                                            Подтвердить
                                        </button>
                                        <a href="{% url 'catalog:list' %}" class="btn btn-lg btn-block btn-warning">Отмена</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4 pb-md-2">{{ object.name }}</h1>
    {% if object.preview %}
        <img src="{{ object.preview|media_filter }}" style="max-height: 300px; max-width: 300px;" class="card-img-top"
                             alt="Продукт">
    {% endif %}
    <p class="lead pt-md-3">{{ object.description }}</p>

    {% if object.price %}
        <p class="lead pt-md-3">Цена: {{ object.price }} р</p>
    {% endif %}
    {% if user == object.owner or perms.catalog.cancellation_of_publication and perms.catalog.changes_the_description and perms.catalog.changes_the_category %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update' object.pk %}">Редактировать</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:delete' object.pk %}">Удалить</a>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6">{{ title }}</h1>
</div>

<div class="container text-center">
    <form method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                            Сохранить изменения
                        {% else %}
                            Добавить товар
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                        {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/basic_template.html' %}
{% block content %}
{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Продукты</h1>
    <hr>
    {% if user.is_authenticate %}
    <a class="p-2 btn btn-primary" href="{% url 'catalog:create' %}">Добавить продукт</a>
</div>
    {% endif %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        {% if object.is_published %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        {% if object.preview %}
                        <img src="{{ object.preview|media_filter }}" style="...    " class="card-img-top"
                             alt="Продукт">
                        {% endif %}
                        <p class="text pt-md-3">{{ object.description|truncatechars:50 }}</p>

                        {% for version in object.version_set.all %}
                            {% if version.number %}
                                <p>Версия: {{version.name }} - {{version.number }}</p>
                            {% endif %}
                        {% endfor %}
                    </ul>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:detail' object.pk %}">О продукте</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}